name: sjfashion_app
description: SJ Fashion Hub Mobile App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.5.0
  flutter_screenutil: ^5.9.3
  persistent_bottom_nav_bar: ^5.0.2

  # Network & API
  http: ^1.2.2
  dio: ^5.7.0

  # Image & Media
  cached_network_image: ^3.3.1
  fancy_shimmer_image: ^2.0.3
  image_picker: ^1.1.2
  photo_view: ^0.14.0

  # UI Components
  flutter_swiper_view: ^1.1.8
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  animate_do: ^3.1.2
  expandable: ^5.0.1

  # Storage & State
  shared_preferences: ^2.2.1
  get_storage: ^2.1.1

  # Utilities
  url_launcher: ^6.1.14
  share_plus: ^7.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# App Icon Configuration
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
