name: app
description: SJ Fashion Hub cross-platform native mobile app
publish_to: 'none' # Remove this line if you intend to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

  # Firebase (for notifications only)
  firebase_core: ^2.30.0
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^17.1.2

  # Networking & Storage
  http: ^1.2.1
  shared_preferences: ^2.2.2
  webview_flutter: ^4.0.6

  # State Management & Utils
  provider: ^6.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
